### ISSUE TITLE
Request to Make AMR Sheetset Manager Package Work W/ Civil 3D 2025

### ISSUE THREAD

**Issue by WrightEngineering** [AdammReilly/AMR_dynSSetMgr#8]
Civil 3D 2025 seems to have broken the nodes available within this package. It would be really wonderful if the package could get an update!

Thanks,
Shaun

**Comment by AdammReilly** [comment]
Added support and published to package manager.

**Comment by WrightEngineering** [comment]
You're amazing. Thank you!
